default:
  http_metas:
    content-type: text/html

  metas:
    title:        Управление доской объявлений
    #description:  symfony project
    #keywords:     symfony, project
    language:     ru
    #robots:       index, follow

  stylesheets:    [sf/sf_admin/css/main.css]

  javascripts:    []

  has_layout:     true
  layout:         layout
