<?php

/**
 * Category
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5925 2009-06-22 21:27:17Z jwage $
 */
class Category extends BaseCategory
{
  /**
   * получить запрос для постранички
   */
  public function getPagerQuery()
  {
    return Doctrine_Query::create()
        ->select('p.*')
        ->from('Post p')
        ->leftJoin('p.Category c')
        ->where('p.category_id = ?', $this->getId())
        ->where('c.lft >= ? AND c.rgt <= ?', array($this->getLft(), $this->getRgt()))
        ->orderBy('p.created_at DESC');
  }
}
