<?php

/**
 * User
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6365 2009-09-15 18:22:38Z jwage $
 */
class User extends BaseUser
{
  public function save(Doctrine_Connection $conn = null)
  {
    if ($this->isNew()) {
      $this->_set('secret', 'dummy');
    }

    return parent::save($conn);
  }
}
