default:
  http_metas:
    content-type: text/html

  metas:
    title:        Наклей - разместить бесплатное объявление
    description:  Бесплатная доска объявлений. Частные лица могут подать объявление бесплатно.
    keywords:     бесплатно, объявление, разместить, подать
    language:     ru
    robots:       index, follow

  stylesheets:    [main.css]

  javascripts:    []

  has_layout:     true
  layout:         layout
